export enum MessageEnum {
    SOCKET_CONNECTED = 'SOCKET_CONNECTED',
    CONNECTED_AND_LISTENING_PORT = 'listening on localhost, port',
    SERVER_USER_FOUND = "SERVER_USER_FOUND",
    USER_CONNECTED = "USER_CONNECTED",
    USER_DISCONNECTED = "USER_DISCONNECTED",
}
